import { Product } from './types';

export const products: Product[] = [
  {
    "id": "P001",
    "name": "Ell Chapo AAA",
    "description": "A premium, heavy-hitting Hybrid with earthy, pine flavors that delivers deep physical relaxation and a calm, happy mind.",
    "category": "Cannabis Flower",
    "price": 120,
    "weight": "1g",
    "availability": "In Stock",
    "sku": "SYS-P001",
    "strainType": "Indoor Hybrid",
    "image": "/Ell Chapo AAA.webp",
    "featured": true,
    "stockCount": 6
  },
  {
    "id": "P002",
    "name": "Tequila Sunrise",
    "description": "A vibrant Hybrid bursting with sweet citrus and fruity flavors, offering a balanced, uplifting high perfect for a sunny day.",
    "category": "Cannabis Flower",
    "price": 80,
    "weight": "1g",
    "availability": "In Stock",
    "sku": "SYS-P002",
    "strainType": "Indoor Hybrid",
    "image": "/Tequila Sunrise.webp",
    "featured": false,
    "stockCount": 7
  },
  {
    "id": "P003",
    "name": "B52",
    "description": "A classic, sweet-tasting Sativa that provides a soaring cerebral buzz and sustained energy to keep you motivated and engaged.",
    "category": "Cannabis Flower",
    "price": 90,
    "weight": "1g",
    "availability": "In Stock",
    "sku": "SYS-P003",
    "strainType": "Indoor Sativa",
    "image": "/B52.webp",
    "featured": false,
    "stockCount": 8
  },
  {
    "id": "P004",
    "name": "Sour Biskot",
    "description": "A potent Indica cross blending sour, diesel notes with sweet, baked goods flavors for profound relaxation and a heavy body high.",
    "category": "Cannabis Flower",
    "price": 120,
    "weight": "1g",
    "availability": "In Stock",
    "sku": "SYS-P004",
    "strainType": "Indoor Indica",
    "image": "/Sour Biskot.webp",
    "featured": false,
    "stockCount": 9
  },
  {
    "id": "P005",
    "name": "Nacho Cheese",
    "description": "A unique, pungent Sativa with a sharp, savory cheese aroma that delivers a clear-headed, uplifting, and creative buzz.",
    "category": "Cannabis Flower",
    "price": 80,
    "weight": "1g",
    "availability": "In Stock",
    "sku": "SYS-P005",
    "strainType": "Indoor Sativa",
    "image": "/Nacho Cheese.webp",
    "featured": false,
    "stockCount": 10
  },
  {
    "id": "P006",
    "name": "Blue Gelato",
    "description": "A fruity and sweet Sativa offering a burst of berry flavors paired with an energizing, mood-elevating high perfect for daytime.",
    "category": "Cannabis Flower",
    "price": 90,
    "weight": "1g",
    "availability": "In Stock",
    "sku": "SYS-P006",
    "strainType": "Indoor Sativa",
    "image": "/Blue-Gelatowebp.webp",
    "featured": false,
    "stockCount": 11
  },
  {
    "id": "P007",
    "name": "Champagne Roze",
    "description": "An elegant Sativa with floral and sweet berry notes, providing a bubbly, euphoric head high that sparks creativity and joy.",
    "category": "Cannabis Flower",
    "price": 100,
    "weight": "1g",
    "availability": "In Stock",
    "sku": "SYS-P007",
    "strainType": "Indoor Sativa",
    "image": "/Champagne Roze.jpg",
    "featured": false,
    "stockCount": 5
  },
  {
    "id": "P008",
    "name": "Ellen Cookii",
    "description": "A vibrant Sativa offering sweet, earthy cookie dough flavors alongside a stimulating and proactive cerebral high.",
    "category": "Cannabis Flower",
    "price": 80,
    "weight": "1g",
    "availability": "In Stock",
    "sku": "SYS-P008",
    "strainType": "Indoor Sativa",
    "image": "/Ellen Cookii.webp",
    "featured": false,
    "stockCount": 6
  },
  {
    "id": "P009",
    "name": "Green House",
    "description": "A sun-kissed, greenhouse-grown Sativa delivering an uplifting and earthy experience, perfect for outdoor activities and creative endeavors.",
    "category": "Cannabis Flower",
    "price": 50,
    "weight": "1g",
    "availability": "In Stock",
    "sku": "SYS-P009",
    "strainType": "Greenhouse Sativa",
    "image": "/Green House.webp",
    "featured": false,
    "stockCount": 7
  },
  {
    "id": "P010",
    "name": "Passion Fizz",
    "description": "A delightfully fruity and effervescent Hybrid offering a balanced, euphoric high that eases the body while stimulating the mind.",
    "category": "Cannabis Flower",
    "price": 90,
    "weight": "1g",
    "availability": "In Stock",
    "sku": "SYS-P010",
    "strainType": "Indoor Hybrid",
    "image": "/Passion Fizz.webp",
    "featured": false,
    "stockCount": 8
  },
  {
    "id": "P011",
    "name": "Mexican Avalanche",
    "description": "A potent and fast-acting Sativa that triggers an avalanche of energetic, cerebral euphoria and creative focus.",
    "category": "Cannabis Flower",
    "price": 90,
    "weight": "1g",
    "availability": "In Stock",
    "sku": "SYS-P011",
    "strainType": "Indoor Sativa",
    "image": "/Mexican Avalanche.webp",
    "featured": false,
    "stockCount": 9
  },
  {
    "id": "P012",
    "name": "Wedding Gelato",
    "description": "A decadently sweet and creamy Indica cross that melts away stress, providing profound full-body relaxation and a peaceful mindset.",
    "category": "Cannabis Flower",
    "price": 80,
    "weight": "1g",
    "availability": "In Stock",
    "sku": "SYS-P012",
    "strainType": "Indoor Indica",
    "image": "/Wedding Gelato.webp",
    "featured": false,
    "stockCount": 10
  },
  {
    "id": "P013",
    "name": "Green House Select",
    "description": "A carefully selected, greenhouse-grown Indica offering rich, earthy aromas and deep, soothing physical relaxation.",
    "category": "Cannabis Flower",
    "price": 40,
    "weight": "1g",
    "availability": "In Stock",
    "sku": "SYS-P013",
    "strainType": "Greenhouse Indica",
    "image": "/Green House.webp",
    "featured": false,
    "stockCount": 11
  },
  {
    "id": "P014",
    "name": "Mint Runtz",
    "description": "A refreshing, sweet, and minty Hybrid that delivers a beautifully balanced high, offering mental clarity alongside physical calm.",
    "category": "Cannabis Flower",
    "price": 70,
    "weight": "1g",
    "availability": "In Stock",
    "sku": "SYS-P014",
    "strainType": "Outdoor Hybrid",
    "image": "/Mint Runtz.webp",
    "featured": false,
    "stockCount": 5
  },
  {
    "id": "P016",
    "name": "Green Door",
    "description": "A robust, earthy Indica cultivated in our greenhouse, designed to open the door to deep rest and total body tranquility.",
    "category": "Cannabis Flower",
    "price": 50,
    "weight": "1g",
    "availability": "In Stock",
    "sku": "SYS-P016",
    "strainType": "Greenhouse Indica",
    "image": "/Green Door.jpeg",
    "featured": false,
    "stockCount": 7
  },
  {
    "id": "P017",
    "name": "Dab Infused Sticks",
    "description": "Premium Sativa pre-rolled joints supercharged with high-quality dab concentrate for an incredibly potent, long-lasting, and energizing experience.",
    "category": "Pre-Rolls",
    "price": 160,
    "weight": "1g",
    "availability": "In Stock",
    "sku": "SYS-P017",
    "strainType": "Sativa",
    "image": "/Dab Infused Sticks.webp",
    "featured": true,
    "stockCount": 8
  },
  {
    "id": "P018",
    "name": "Green Door Moonsticks",
    "description": "Premium cannabis pre-rolls infused with concentrate and rolled in kief for a potent, out-of-this-world experience.",
    "category": "Pre-Rolls",
    "price": 80,
    "weight": "1g",
    "availability": "In Stock",
    "sku": "SYS-P018",
    "strainType": "N/A",
    "image": "/Green Door Moonsticks.webp",
    "featured": false,
    "stockCount": 9
  },
  {
    "id": "P019",
    "name": "Hybrid Moonsticks",
    "description": "Levels up, keeps you not too low, not too high. For an easy day.",
    "category": "Pre-Rolls",
    "price": 65,
    "weight": "1g",
    "availability": "In Stock",
    "sku": "SYS-P019",
    "strainType": "Sativa Dominant Hybrid",
    "image": "/Hybrid Moonsticks.webp",
    "featured": false,
    "stockCount": 10
  },
  {
    "id": "P020",
    "name": "Gorilla Glue",
    "description": "Elevates your mood, brings energy, keeps you proactive.",
    "category": "Cannabis Flower",
    "price": 110,
    "weight": "1g",
    "availability": "In Stock",
    "sku": "SYS-P020",
    "strainType": "Indoor Sativa",
    "image": "/Gorilla Glue.jpeg",
    "featured": false,
    "stockCount": 11
  },
  {
    "id": "P021",
    "name": "Pre-Roll (Indoor)",
    "description": "Elevates your mood, brings energy, keeps you proactive.",
    "category": "Pre-Rolls",
    "price": 50,
    "weight": "1 pc",
    "availability": "In Stock",
    "sku": "SYS-P021",
    "strainType": "Sativa",
    "image": "/Pre-Roll (Indoor).webp",
    "featured": false,
    "stockCount": 5
  },
  {
    "id": "P022",
    "name": "Pre-Roll (Outdoor)",
    "description": "Drops your energy, sleeping pill, for full relaxation.",
    "category": "Pre-Rolls",
    "price": 10,
    "weight": "1 pc",
    "availability": "In Stock",
    "sku": "SYS-P022",
    "strainType": "Indica",
    "image": "/Pre-Roll (Outdoor).webp",
    "featured": false,
    "stockCount": 6
  },
  {
    "id": "P023",
    "name": "Pre-Roll (Green House)",
    "description": "Convenient and ready-to-smoke pre-rolled joints, packed with quality greenhouse-grown cannabis flower.",
    "category": "Pre-Rolls",
    "price": 30,
    "weight": "1 pc",
    "availability": "In Stock",
    "sku": "SYS-P023",
    "strainType": "N/A",
    "image": "/Pre-Roll (Green House).jpg",
    "featured": false,
    "stockCount": 7
  },
  {
    "id": "P024",
    "name": "Color of Spades",
    "description": "Drops your energy, sleeping pill, for full relaxation.",
    "category": "Cannabis Flower",
    "price": 150,
    "weight": "1g",
    "availability": "In Stock",
    "sku": "SYS-P024",
    "strainType": "Indoor Indica",
    "image": "/Color of Spades.webp",
    "featured": false,
    "stockCount": 8
  },
  {
    "id": "P025",
    "name": "Muffins",
    "description": "Freshly baked, cannabis-infused muffins offering a delicious and discreet way to enjoy a satisfying, long-lasting high.",
    "category": "Edibles",
    "price": 50,
    "weight": "1 pc",
    "availability": "In Stock",
    "sku": "SYS-P025",
    "strainType": "N/A",
    "image": "https://images.unsplash.com/photo-1607958996333-41aef7caefaa?auto=format&fit=crop&q=80&w=800",
    "featured": false,
    "stockCount": 9
  },
  {
    "id": "P026",
    "name": "Gummies",
    "description": "Sweet and chewy fruit gummies, precisely dosed with premium cannabis extract for a flavorful and elevated experience.",
    "category": "Edibles",
    "price": 50,
    "weight": "1 pack",
    "availability": "In Stock",
    "sku": "SYS-P026",
    "strainType": "N/A",
    "image": "/Gummies.webp",
    "featured": true,
    "stockCount": 10
  },
  {
    "id": "P027",
    "name": "Dab Hit",
    "description": "High-potency cannabis concentrate crafted for experienced users, delivering intense flavor and immediate effects.",
    "category": "Concentrates",
    "price": 30,
    "weight": "1 dose",
    "availability": "In Stock",
    "sku": "SYS-P027",
    "strainType": "N/A",
    "image": "/Dab Hit.png",
    "featured": false,
    "stockCount": 11
  },
  {
    "id": "P028",
    "name": "Cannabis Soda POPS SODA",
    "description": "A crisp, refreshing cannabis-infused carbonated beverage perfect for a fast-acting, drinkable high.",
    "category": "Edibles",
    "price": 50,
    "weight": "300ml",
    "availability": "In Stock",
    "sku": "SYS-P028",
    "strainType": "N/A",
    "image": "/Cannabis Soda POPS SODA.webp",
    "featured": false,
    "stockCount": 5
  },
  {
    "id": "P029",
    "name": "Cannabis Soda GREEN GIANT",
    "description": "A larger, potent cannabis-infused soda packed with bold flavors and uplifting effects for any occasion.",
    "category": "Edibles",
    "price": 100,
    "weight": "500ml",
    "availability": "In Stock",
    "sku": "SYS-P029",
    "strainType": "N/A",
    "image": "/Cannabis Soda GREEN GIANT.webp",
    "featured": false,
    "stockCount": 6
  },
  {
    "id": "P030",
    "name": "G Pen Dash Vaporizer",
    "description": "Compact and lightweight dry herb vaporizer featuring a durable aluminum alloy body and glass-glazed stainless steel heating chamber.",
    "category": "Vapes",
    "price": 860,
    "weight": "9000 Pulls",
    "availability": "In Stock",
    "sku": "SYS-P030",
    "strainType": "Sativa",
    "image": "/g-pen-dash.png",
    "featured": true,
    "stockCount": 7
  },
  {
    "id": "P031",
    "name": "Vape Cartridge (Skywalker)",
    "description": "Premium Sativa vape cartridge delivering smooth, flavorful vapor. Perfect for raising your spirits, blazing, and unlocking creativity.",
    "category": "Vapes",
    "price": 450,
    "weight": "1 pc",
    "availability": "In Stock",
    "sku": "SYS-P031",
    "strainType": "Sativa",
    "image": "/Vape Cartridge(Skywalker).webp",
    "featured": false,
    "stockCount": 8
  },
  {
    "id": "P032",
    "name": "Vape Cartridge (Tooti Fruity)",
    "description": "Deliciously fruity Sativa vape cartridge designed for the perfect wake and bake. Get going with an energetic and uplifting high.",
    "category": "Vapes",
    "price": 450,
    "weight": "1 pc",
    "availability": "In Stock",
    "sku": "SYS-P032",
    "strainType": "Sativa",
    "image": "/Vape Cartridge (Tooti Fruity).webp",
    "featured": false,
    "stockCount": 9
  },
  {
    "id": "P033",
    "name": "Hemp Wraps",
    "description": "Natural, tobacco-free hemp wraps designed for a slow, even burn and a smooth, pure rolling experience.",
    "category": "Accessories",
    "price": 20,
    "weight": "1 pc",
    "availability": "In Stock",
    "sku": "SYS-P033",
    "strainType": "N/A",
    "image": "/Hemp Wraps.webp",
    "featured": false,
    "stockCount": 10
  },
  {
    "id": "P034",
    "name": "OHIS Tubes (Container)",
    "description": "Durable, smell-proof OHIS Rolling Club joint tubes, perfect for keeping your pre-rolls fresh and protected on the go.",
    "category": "Accessories",
    "price": 20,
    "weight": "1 pc",
    "availability": "In Stock",
    "sku": "SYS-P034",
    "strainType": "N/A",
    "image": "/OHIS Tubes (Container).webp",
    "featured": false,
    "stockCount": 11
  },
  {
    "id": "P035",
    "name": "Lighter",
    "description": "A reliable, pocket-sized lighter essential for sparking up your favorite flower, pre-rolls, or concentrates.",
    "category": "Accessories",
    "price": 15,
    "weight": "1 pc",
    "availability": "In Stock",
    "sku": "SYS-P035",
    "strainType": "N/A",
    "image": "/Lighter.jpg",
    "featured": false,
    "stockCount": 5
  },
  {
    "id": "P036",
    "name": "Rolling Paper",
    "description": "Ultra-thin, unrefined natural rolling papers ensuring an even burn and preserving the authentic flavor of your flower.",
    "category": "Accessories",
    "price": 30,
    "weight": "1 pc",
    "availability": "In Stock",
    "sku": "SYS-P036",
    "strainType": "N/A",
    "image": "/Rolling Paper.webp",
    "featured": false,
    "stockCount": 6
  }
];

export const WHATSAPP_NUMBER = import.meta.env.VITE_WHATSAPP_NUMBER || "27785870868";



if (import.meta.env.DEV) {
  const ids = new Set();
  const skus = new Set();
  products.forEach(p => {
    if (ids.has(p.id)) {
      console.warn(`[DEV WARNING] Duplicate product ID found: ${p.id}`);
    }
    ids.add(p.id);
    
    if (skus.has(p.sku)) {
      console.warn(`[DEV WARNING] Duplicate product SKU found: ${p.sku}`);
    }
    skus.add(p.sku);
  });
}
